---
- name: Check if .aliases is already defined
  lineinfile:
    state: absent
    path: "$HOME/.zshrc"
    regexp: "^source $HOME/.aliases"
  check_mode: true
  changed_when: false
  register: check_aliases_is_sourced

- name: Ensure .aliases is setup
  lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source $HOME/.aliases"
  when: check_aliases_is_sourced.found == 0