---
- name: Check if asdf-completion is already defined
  lineinfile:
    state: absent
    path: "$HOME/.zshrc"
    regexp: "^source $HOME/.asdf/asdf.sh"
  check_mode: true
  changed_when: false
  register: check_asdf_completion

- name: Ensure asdf-completion is setup
  lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source $HOME/.asdf/asdf.sh"
  when: check_asdf_completion.found == 0

- name: Check if asdf-direnv is already defined
  lineinfile:
    state: absent
    path: "$HOME/.zshrc"
    regexp: "^source \"$HOME/.config/asdf-direnv/zshrc\""
  check_mode: true
  changed_when: false
  register: check_asdf_direnv

- name: Ensure asdf-direnv is setup
  lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source \"$HOME/.config/asdf-direnv/zshrc\""
  when: check_asdf_direnv.found == 0
