---
- name: Check if docker start is already defined
  lineinfile:
    state: absent
    path: "$HOME/.zshrc"
    regexp: "^colima start > /dev/null 2>&1"
  check_mode: true
  changed_when: false
  register: check_docker_start

- name: Run docker if not already started
  lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "colima start > /dev/null 2>&1"
  when: check_docker_start.found == 0