---
- name: Setup macos machine
  hosts: macos
  gather_facts: yes
  become: false
  vars:
    computername: gaia
    hostname: gaia
  vars_files:
    - vars/common.yml
    - vars/macos.yml
  roles:
    - role: elliotweiser.osx-command-line-tools
      when: ansible_distribution == 'MacOSX'
    - role: geerlingguy.mac.homebrew
      when: ansible_distribution == 'MacOSX'
    - role: geerlingguy.mac.mas
      when: ansible_distribution == 'MacOSX'
    - role: geerlingguy.mac.dock
      when: ansible_distribution == 'MacOSX'
    - role: macos
      when: ansible_distribution == 'MacOSX'

- name: Setup common dev environment
  hosts: all
  gather_facts: yes
  become: false
  vars_files:
    - vars/common.yml
    - vars/git.yml
  roles:
    - role: common
    - role: git
    - role: dotfiles
    - role: zsh
    - role: asdf