---
- name: Setup macos machine
  hosts: macos
  gather_facts: yes
  become: no
  vars:
    computername: gaia
    hostname: gaia
  vars_files:
    - vars/common.yml
    - vars/macos.yml
  roles:
    - role: elliotweiser.osx-command-line-tools
      when: ansible_distribution in ['MacOSX']
    - role: geerlingguy.mac.homebrew
      when: ansible_distribution in ['MacOSX']
    - role: geerlingguy.mac.mas
      when: ansible_distribution in ['MacOSX']
    - role: geerlingguy.mac.dock
      when: ansible_distribution in ['MacOSX']
    - role: macos
      when: ansible_distribution in ['MacOSX']

- name: Setup debian environment
  hosts:
    - debian
  gather_facts: yes
  become: no
  vars:
    computername: zeus
    hostname: zeus
  vars_files:
    - debian
  roles:
    - role: debian
      when: ansible_distribution in ['Debian']

- name: Setup common dev environment
  hosts:
    - macos
    - debian
  gather_facts: yes
  become: no
  vars_files:
    - vars/common.yml
    - vars/git.yml
  roles:
    - role: common
    - role: asdf
    - role: zsh
    - role: git
    - role: dotfiles