---
- name: Restart Finder
  ansible.builtin.command: killall Finder
  changed_when: true

- name: Restart code-server
  ansible.builtin.command:
    cmd: brew services restart code-server
  changed_when: true

- name: Restart immich-ml
  community.general.launchd:
    name: local.immich-ml
    state: restarted
