---
- name: Ensure stow is installed
  command: command -v stow
  register: stow_result
  failed_when: stow_result == ""
  changed_when: false

- name: Ensure dotfiles project exists
  file:
    path: "{{ ansible_env.HOME }}/workspace/code/dotfiles"
    state: directory
    follow: true

- name: Stow dotfiles in home directory
  ansible.builtin.shell:
    cmd: stow --stow --verbose --target={{ ansible_env.HOME }} .
    chdir: "{{ ansible_env.HOME }}/workspace/code/dotfiles"
  changed_when: true