---
- name: Ensure stow is installed
  ansible.builtin.command: which stow
  register: stow_result
  failed_when: stow_result.rc != 0
  changed_when: false

- name: Ensure dotfiles project exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/workspace/code/{{ git_username }}/dotfiles"
    state: directory
    follow: true
    mode: "0755"

- name: Stow dotfiles in home directory
  ansible.builtin.shell:
    cmd: stow --stow --verbose --target={{ ansible_facts.env.HOME }} .
    chdir: "{{ ansible_facts.env.HOME }}/workspace/code/{{ git_username }}/dotfiles"
  register: stow_result
  changed_when: "'LINK' in stow_result.stderr"
