---
- name: Add Docker GPG apt key
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: arm64
    signed_by: https://download.docker.com/linux/debian/gpg

- name: Update apt and install Docker packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin