---
- name: Add Libretro repository
  command: add-apt-repository ppa:libretro/stable

- name: Update apt and install gaming packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - retroarch
    - libretro-*