---
- include_tasks: programs.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- include_tasks: docker.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- include_tasks: jetbrains.yml
  when: enable_debian_gui and ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- include_tasks: media.yml
  when: enable_debian_gui and ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- include_tasks: gaming.yml
  when: enable_debian_gui and ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'