---
- name: Add Mozilla repository
  deb822_repository:
    name: mozilla
    state: present
    types: [deb]
    uris: "https://packages.mozilla.org/apt"
    suites: [mozilla]
    components: [main]
    signed_by: "https://packages.mozilla.org/apt/repo-signing-key.gpg"
    enabled: yes

- name: Update apt and install media packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - firefox

- name: Pull syncthing image
  community.docker.docker_image_pull:
    name: syncthing/syncthing
    tag: latest

- name: Start syncthing
  community.docker.docker_container:
    image: syncthing/syncthing:latest
    name: "syncthing-{{ computername }}"
    hostname: "syncthing-{{ computername }}"
    volumes:
      - "{{ ansible_env.HOME }}:/var/syncthing"
    ports:
     - "8384:8384"
     - "22000:22000/tcp"
     - "22000:22000/udp"
     - "21027:21027/udp"
    detach: true
    output_logs: false