---
- name: Add common development tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - software-properties-common
    - autoconf
    - automake
    - gcc
    - g++
    - apt-transport-https
    - build-essential
    - ca-certificates
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - liblzma-dev
    - libncurses-dev
    - tk-dev
    - unzip
    - wget
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add apt programs
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: true
  loop: "{{ apt_programs | default([]) }}"
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add snap classic programs
  command: "snap install --classic {{ item }}"
  loop: "{{ snap_classic_programs | default([]) }}"
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add snap programs
  command: "snap install {{ item }}"
  loop: "{{ snap_programs | default([]) }}"
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
