---
- name: Get current ComputerName
  ansible.builtin.command: scutil --get ComputerName
  register: computername_result
  changed_when: false
  check_mode: false
  when: computername is not none

- name: Update ComputerName
  ansible.builtin.command: scutil --set ComputerName "{{ computername }}"
  become: true
  when: computername is not none and (computername not in computername_result.stdout)
  changed_when: true

- name: Get current HostName
  ansible.builtin.command: scutil --get HostName
  register: hostname_result
  changed_when: false
  failed_when: false
  check_mode: false
  when: hostname is not none

- name: Update HostName
  ansible.builtin.command: scutil --set HostName {{ hostname }}
  become: true
  when: hostname is not none and (hostname_result.failed or (hostname not in hostname_result.stdout))
  changed_when: true

- name: Get current LocalHostName
  ansible.builtin.command: scutil --get LocalHostName
  register: localhostname_result
  changed_when: false
  check_mode: false
  when: hostname is not none

- name: Update LocalHostName
  ansible.builtin.command: scutil --set LocalHostName {{ hostname }}
  become: true
  when: hostname is not none and (hostname not in localhostname_result.stdout)
  changed_when: true
