---
- name: Install Homebrew packages and apps
  ansible.builtin.import_tasks: homebrew.yml

- name: Configure hostname
  ansible.builtin.import_tasks: hostname.yml
  when: ansible_facts.distribution == 'MacOSX'

- name: Configure system preferences
  ansible.builtin.import_tasks: system.yml
  when: ansible_facts.distribution == 'MacOSX'

- name: Setup code-server service
  ansible.builtin.import_tasks: code-server.yml
  when: ansible_facts.distribution == 'MacOSX'

- name: Setup immich-ml service
  ansible.builtin.import_tasks: immich-ml.yml
  when: ansible_facts.distribution == 'MacOSX'
