---
- name: Ensure asdf is installed
  command: command -v asdf
  register: asdf_result

- name: Get latest release of asdf
  community.general.github_release:
    user: asdf-vm
    repo: asdf
    action: latest_release
  register: asdf_latest_release

- name: Set latest asdf version
  set_fact:
    asdf_latest_version: "{{ asdf_latest_release.tag }}"

- name: Download latest asdf
  ansible.builtin.get_url:
    url: "https://github.com/asdf-vm/asdf/releases/download/{{ asdf_latest_version }}/asdf-{{ asdf_latest_version }}-{{ ansible_os_family | lower }}-{{ ansible_architecture }}.tar.gz"
    dest: "/tmp/asdf-{{ asdf_latest_version }}.tar.gz"

- name: Unarchive and install latest asdf
  command: "tar -xvzf /tmp/asdf-{{ asdf_latest_version }}.tar.gz && mv asdf /usr/local/bin && rm -rf /tmp/asdf-{{ asdf_latest_version }}.tar.gz"
  become: true
  when: asdf_result is failed

- name: Add asdf plugins
  command: "asdf plugin add {{ item.name }} {{ item.url }}"
  loop: "{{ asdf_plugins }}"

- name: Run asdf post install script for plugins
  command: "{{ item.post_install }}"
  loop: "{{ asdf_plugins }}"
  when: "'post_install' in item"

- name: Check if .tool-versions file exists
  stat:
    path: "{{ ansible_env.HOME }}/.tool-versions"
  register: tool_versions_file_result

- name: Run asdf install
  command: "asdf install"
  when: tool_versions_file_result.stat.exists