---
- name: Ensure asdf support
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source $HOME/.asdf/asdf.sh"

- name: Ensure asdf-completion support
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source $HOME/.asdf/completions/asdf.bash"

- name: Ensure asdf-direnv support
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source \"$HOME/.config/asdf-direnv/zshrc\""

- name: Ensure asdf-golang support
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source \"$HOME/.asdf/plugins/golang/set-env.zsh\""

- name: Ensure asdf-java support
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "source \"$HOME/.asdf/plugins/java/set-java-home.zsh\""