---
- name: Ensure asdf support
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zsh_dynamic"
    line: "export ASDF_DATA_DIR=\"$HOME/.asdf\""

- name: Add asdf shims
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zsh_dynamic"
    line: "export PATH=\"$ASDF_DATA_DIR/shims:$PATH\""

# - name: Ensure asdf-java support
#   ansible.builtin.lineinfile:
#     state: present
#     path: "$HOME/.zsh_dynamic"
#     line: "[[ -f \"$HOME/.asdf/plugins/java/set-java-home.zsh\" ]] && . \"$HOME/.asdf/plugins/java/set-java-home.zsh\""
