---

- name: Ensure homebrew-path is set
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zsh-dynamic"
    line: "export PATH=$(brew --prefix)/bin:$PATH"
  when: ansible_distribution == 'MacOSX'