---

- name: Ensure homebrew-path is set
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "export PATH=$(brew --prefix)/bin:$PATH"
  when: ansible_distribution in ['MacOSX']