---
- name: Ensure zsh is installed
  ansible.builtin.command: which zsh
  register: zsh_result
  failed_when: zsh_result.rc != 0
  changed_when: false

- name: Set login shell of user {{ ansible_facts.env.USER }} to /bin/zsh
  ansible.builtin.user:
    name: "{{ ansible_facts.env.USER }}"
    shell: /bin/zsh
  become: true

- name: Create zsh-dynamic file
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.zsh_dynamic"
    state: touch
    mode: "0644"

- name: Setup Oh My Zsh
  ansible.builtin.import_tasks: oh-my-zsh.yml

- name: Setup zsh dotfiles
  ansible.builtin.import_tasks: dotfiles.yml

- name: Setup macOS-specific paths
  ansible.builtin.import_tasks: macos.yml
  when: ansible_facts.distribution == 'MacOSX'

- name: Setup Node.js paths
  ansible.builtin.import_tasks: node.yml

- name: Setup secrets
  ansible.builtin.import_tasks: secrets.yml
