---

- name: Ensure zsh is installed
  command: command -v zsh
  register: zsh_result
  failed_when: zsh_result == ""
  changed_when: false

- include_tasks: oh-my-zsh.yml
- include_tasks: asdf.yml
- include_tasks: node.yml
- include_tasks: dotfiles.yml
- include_tasks: macos.yml
  when: ansible_distribution in ['MacOSX']
