---
- name: Ensure global node_modules directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.npm-packages/lib/node_modules"
    state: directory
    follow: true
    mode: "0755"

- name: Ensure global node bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.npm-packages/bin"
    state: directory
    follow: true
    mode: "0755"

- name: Add nodejs path to PATH
  ansible.builtin.lineinfile:
    state: present
    path: "{{ ansible_facts.env.HOME }}/.zsh_dynamic"
    line: "export PATH=$HOME/.npm-packages/bin:$PATH"

- name: Add node path to PATH
  ansible.builtin.lineinfile:
    state: present
    path: "{{ ansible_facts.env.HOME }}/.zsh_dynamic"
    line: "export NODE_PATH=$HOME/.npm-packages/lib/node_modules"
