---
- name: Ensure global node_modules directory exists
  file:
    path: $HOME/.npm-packages/lib/node_modules
    state: directory
    follow: true

- name: Ensure global node bin directory exists
  file:
    path: $HOME/.npm-packages/bin
    state: directory
    follow: true

- name: Add nodejs path to PATH
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zsh-dynamic"
    line: "export PATH=$HOME/.npm-packages/bin:$PATH"

- name: Add node path to PATH
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zsh-dynamic"
    line: "export NODE_PATH=$HOME/.npm-packages/lib/node_modules"
