---
- name: Check if Oh-my-zsh exists
  stat:
    path: $HOME/.oh-my-zsh
  register: ohmyzsh_result
  changed_when: false

- name: Download Oh-my-zsh
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "$HOME/.oh-my-zsh-tmp"
    recursive: true
    accept_hostkey: false
    depth: 1
  when: not ohmyzsh_result.stat.exists

- name: Check if .zshrc exists
  stat:
    path: $HOME/.zshrc
  register: zshrc_result
  changed_when: false

- name: Install Oh-my-zsh
  command: "$HOME/.oh-my-zsh-tmp/tools/install.sh"
  when: not zshrc_result.stat.exists

- name: Check if zsh-autosuggestions plugins installed
  stat:
    path: "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: zsh_autosuggestions_result
  changed_when: false

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    recursive: true
    accept_hostkey: false
    depth: 1
  when: not zsh_autosuggestions_result.stat.exists

- name: Check if zsh-completions plugins installed
  stat:
    path: "$HOME/.oh-my-zsh/custom/plugins/zsh-completions"
  register: zsh_completions_result
  changed_when: false

- name: Install zsh-completions plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-completions.git"
    dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-completions"
    recursive: true
    accept_hostkey: false
    depth: 1
  when: not zsh_completions_result.stat.exists

- name: Check if zsh-syntax-highlighting plugins installed
  stat:
    path: "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  register: zsh_syntaxhighlighting_result
  changed_when: false

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    recursive: true
    accept_hostkey: false
    depth: 1
  when: not zsh_syntaxhighlighting_result.stat.exists
