---
- name: Check if Prezto exists
  stat:
    path: "{{ ansible_env.HOME }}/.zprezto"
  register: prezto_result
  changed_when: false

- name: Install Prezto
  ansible.builtin.git:
    repo: "https://github.com/sorin-ionescu/prezto.git"
    dest: "{{ ansible_env.HOME }}/.zprezto"
    recursive: true
    accept_hostkey: false
    version: master
  when: not prezto_result.stat.exists

- name: Link all Prezto files
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.zprezto/runcoms/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    state: link
  loop:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
    - zshrc
