---
- name: Add cargo path to PATH
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: "export PATH=$HOME/.cargo/bin:$PATH"

- name: Add rustup bin path to PATH
  ansible.builtin.lineinfile:
    state: present
    path: "$HOME/.zshrc"
    line: 'export PATH="$(brew --prefix)/opt/rustup/bin:$PATH"'
  when: ansible_distribution in ['MacOSX']