---

- name: Ensure vim is installed
  command: command -v vim
  register: vim_result
  failed_when: vim_result == ""
  changed_when: false

- name: Ensure gpg2 is installed
  command: command -v gpg2
  register: gpg2_result
  failed_when: gpg2_result == ""
  changed_when: false

- name: Ensure git-delta is installed
  command: command -v delta
  register: delta_result
  failed_when: delta_result == ""
  changed_when: false

- name: Updating git global config values
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ git_configs }}"
