---
- name: Ensure git is installed
  ansible.builtin.command: which git
  register: git_result
  failed_when: git_result.rc != 0
  changed_when: false

- name: Configure git
  ansible.builtin.import_tasks: config.yml

- name: Setup git projects
  ansible.builtin.import_tasks: projects.yml
