---
- name: Ensure developer directory exists
  ansible.builtin.file:
    path: "{{ git_projects_dir }}"
    state: directory
    follow: true
    mode: "0755"

- name: Backup project repos
  ansible.builtin.shell: |
    {{ playbook_dir }}/../scripts/backup-git-repos.sh {{ git_projects_dir }}
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
  register: backup_repos_result
  changed_when: "'Successfully' in backup_repos_result.stdout"
  failed_when: backup_repos_result.rc != 0
