---
- name: Update timezone to '{{ timezone }}'
  community.general.timezone:
    name: "{{ timezone }}"
  become: true

- name: Configure SSH
  ansible.builtin.import_tasks: ssh.yml
  when: configure_ssh
