---
- name: Ensure vim is installed
  ansible.builtin.command: which vim
  register: vim_result
  failed_when: vim_result.rc != 0
  changed_when: false

- name: Create vim directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.vim"
    state: directory
    mode: "0755"

- name: Create vim-autoload directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.vim/autoload"
    state: directory
    mode: "0755"

- name: Check if vim-plug is downloaded
  ansible.builtin.stat:
    path: "{{ ansible_facts.env.HOME }}/.vim/autoload/plug.vim"
  register: vim_plug_file_result

- name: Download vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_facts.env.HOME }}/.vim/autoload/plug.vim"
    mode: "0755"
  when: not vim_plug_file_result.stat.exists

- name: Check if vim-plug is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts.env.HOME }}/.vim/plugged"
  register: vim_plug_directory_result

- name: Setup vim plugins
  ansible.builtin.command: vim +'PlugInstall --sync' +qa
  when: not vim_plug_directory_result.stat.exists
  changed_when: true
