---
- name: Setup macos machine
  hosts: macos
  gather_facts: true
  vars:
    computername: gaia
    hostname: gaia
  vars_files:
    - ../vars/common.yml
    - ../vars/macos.yml
  roles:
    - role: macos

- name: Setup common dev environment
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/common.yml
    - ../vars/git.yml
  roles:
    - role: common
    - role: git
    - role: vim
    - role: dotfiles
    - role: zsh
    - role: mise
