---

- name: daemon_reload
  systemd:
    daemon_reload: yes

- name: Unstow dotfiles from home directory
  ansible.builtin.shell:
    cmd: stow --delete --verbose --target=$HOME .
    chdir: "$HOME/workspace/code/dotfiles"
  changed_when: true